name: SonarQube .NET analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  sonar-dotnet:
    runs-on: [self-hosted, windows]

    env:
      SONAR_HOST_URL: "http://192.168.7.179:9000"
      SONAR_PROJECT_KEY: "ucnl_AzimuthSuite_55067894-0518-4dee-b96c-56c08b52006d"
      SONAR_PROJECT_NAME: "ucnl/AzimuthSuite"
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install / Update SonarScanner for .NET
        run: |
          dotnet tool update --global dotnet-sonarscanner 2>$null
          if ($LASTEXITCODE -ne 0) {
            dotnet tool install --global dotnet-sonarscanner
          }

      - name: SonarQube begin
        run: |
          dotnet sonarscanner begin `
            /k:"$env:SONAR_PROJECT_KEY" `
            /n:"$env:SONAR_PROJECT_NAME" `
            /d:sonar.host.url="$env:SONAR_HOST_URL" `
            /d:sonar.token="$env:SONAR_TOKEN"

      - name: Build solution
        run: >
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe"
          AzimuthSuite.csproj
          /t:Rebuild
          /p:Configuration=Release

      - name: SonarQube end
        run: dotnet sonarscanner end /d:sonar.token="$env:SONAR_TOKEN"
