name: SonarQube .NET analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  sonar-dotnet:
    runs-on: self-hosted        # раннер с меткой self-hosted
    env:
      SONAR_HOST_URL: "http://192.168.7.179:9000"   # тот же URL, что и в UI
      SONAR_PROJECT_KEY: "ucnl_AzimuthSuite_55067894-0518-4dee-b96c-56c08b52006d"
      SONAR_PROJECT_NAME: "ucnl/AzimuthSuite"
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure dotnet tools in PATH
        run: echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      - name: Install / Update SonarScanner for .NET
        run: |
          dotnet tool update --global dotnet-sonarscanner || \
          dotnet tool install --global dotnet-sonarscanner

      - name: SonarQube begin
        run: |
          dotnet sonarscanner begin \
            /k:"$SONAR_PROJECT_KEY" \
            /n:"$SONAR_PROJECT_NAME" \
            /d:sonar.host.url="$SONAR_HOST_URL" \
            /d:sonar.token="$SONAR_TOKEN"

      - name: Build solution
        run: dotnet build --no-incremental
        # при необходимости подставь конкретный .sln:
        # run: dotnet build AzimuthSuite.sln --no-incremental

      - name: SonarQube end
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
