name: SonarQube

on:
  push:
    branches:
      - main   # твоя основная ветка
  workflow_dispatch:   # ← это даёт кнопку Run workflow в UI


jobs:
  sonar:
    runs-on: self-hosted   # или self-hosted, если поднимешь своего runner-а
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # важно: без shallow clone для корректного анализа истории:contentReference[oaicite:16]{index=16}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=ucnl_AzimuthSuite_55067894-0518-4dee-b96c-56c08b52006d
            -Dsonar.projectName=ucnl/AzimuthSuite
            -Dsonar.sources=.
